# Generated by Django 3.0.3 on 2020-06-08 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnvExposure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exposure_name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='GeneMutation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene_name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField()),
                ('has_siblings', models.BooleanField()),
                ('reviewed_status', models.CharField(choices=[('Not Reviewed', 'Not Reviewed'), ('Reviewed - Accepted', 'Reviewed - Accepted'), ('Reviewed - Not Accepted', 'Reviewed - Not Accepted')], default='Not Reviewed', max_length=255)),
                ('env_exposures', models.ManyToManyField(to='fdn_participant.EnvExposure')),
                ('gene_mutations', models.ManyToManyField(to='fdn_participant.GeneMutation')),
            ],
        ),
    ]
