REVIEW_STATUS_NOT_REVIEWED = 'Not Reviewed'
REVIEW_STATUS_ACCEPTED = 'Reviewed - Accepted'
REVIEW_STATUS_NOT_ACCEPTED = 'Reviewed - Not Accepted'


REVIEW_STATUS_CHOICES = [
    (REVIEW_STATUS_NOT_REVIEWED, REVIEW_STATUS_NOT_REVIEWED),
    (REVIEW_STATUS_ACCEPTED, REVIEW_STATUS_ACCEPTED),
    (REVIEW_STATUS_NOT_ACCEPTED, REVIEW_STATUS_NOT_ACCEPTED),
]
